Updated IDs
samjbmason/punkapi pull request #40
Opened 2018-12-12 05:16 UTC by johnjenkman

Updated all IDs to match the recipe ID number from DIY Dog 2018.

2019-01-07 20:46 UTC, samjbmason commented
Thanks for doing this, however, updating all the ID's like this might break other peoples app's so I would be happy to add the new recipes but cant switch the ID's

2019-01-07 20:47 UTC, sammdec requested changes
As mentioned in my comment I cant change the ID's until a potential V3

2019-01-07 23:00 UTC, johnjenkman reviewed
No worries. All good. With the release of DIY Dog 2019 later this year it would be good to create a V3 branch and fix this up.

2019-01-08 13:53 UTC, sammdec approved these changes

2019-01-08 13:53 UTC, merged